<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <LangVersion>12</LangVersion>

    <Version>1.0.0</Version>

    <PackageId>Mastersign.WpfCodeEditor</PackageId>
    <Title>Mastersign WPF Code Editor Control</Title>
    <Authors>Tobias Kiertscher</Authors>
    <Copyright>Copyright © 2025 Tobias Kiertscher</Copyright>
    <Company>Mastersign</Company>
    <Description>
      WPF control for editing JSON and YAML with syntax highlighting and JSON schema support.
      With this capability it is well suited for editing configuration files and data models.
      Based on the Monaco editor from Visual Studio Code.
    </Description>
    <PackageTags>WPF;Control;Editor;Text;JSON;YAML;Schema</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <RepositoryUrl>https://github.com/mastersign/Mastersign.WpfCodeEditor.git</RepositoryUrl>
    <PackageOutputPath>..\dist</PackageOutputPath>
    
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE.md" Pack="true" PackagePath="\"/>
    <None Include="README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="monaco.zip" />
  </ItemGroup>

  <ItemGroup>
    <Reference Condition="'$(TargetFramework)' == 'net48'" Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="[9.0,)" />
    <PackageReference Condition="'$(TargetFramework)' == 'net48'" Include="System.IO.Compression" Version="4.*" />
    
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3179.45" />
  </ItemGroup>

</Project>
